apiVersion: apps/v1
kind: Deployment
metadata:
  name: wigarn-postgres
  labels:
    app: wigarn-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wigarn-postgres
  template:
    metadata:
      labels:
        app: wigarn-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: wigarn
            - name: POSTGRES_USER
              value: wigarn
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wigarn-postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: wigarn-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: wigarn-postgres
