apiVersion: apps/v1
kind: Deployment
metadata:
  name: wigarn-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wigarn-web
  template:
    metadata:
      labels:
        app: wigarn-web
    spec:
      containers:
        - name: web
          image: your-docker-registry/wigarn-web:latest
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: wigarn-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: wigarn-web
