name: 'Ran Ah Rai CI/CD' #Workflow name

on: # Trigger the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    steps:
      - name: 'checkout_code'
        uses: actions/checkout@v5

      - name: "'setup_node"
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 'Enable Corepack (for Yarn 4)'
        run: |
          corepack enable
          corepack prepare yarn@^4.0.0 --activate

      - name: 'install_dependencies'
        run: yarn install

      - name: 'Build Turborepo'
        run: yarn turbo run build --filter=...
