name: 'Ran Ah Rai CI/CD' #Workflow name

on: # Trigger the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint-and-build:
    name: Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout_code'
        uses: actions/checkout@v5

      - name: 'Setup Bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 'install_dependencies'
        run: bun install

      - name: Run linter
        run: bun lint

      - name: 'Build Turborepo'
        run: |
          bun run web:build
          bun run api:build
