name: 'Ran Ah Rai CI/CD' #Workflow name

on: # Trigger the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    steps:
      - name: 'checkout_code'
        uses: actions/checkout@v5

      - name: "'setup_node"
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 'Setup Bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 'install_dependencies'
        run: bun install

      - name: 'Build Turborepo'
        run: |
          bun run web:build
          bun run api:build
